---
name: Validate Policies

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Mondoo Client
        run: |
            echo Installing Mondoo Client...
            echo ${{ inputs.service-account-credentials }} | base64 -d > mondoo.json
            curl -sSL https://mondoo.com/install.sh | bash
        shell: bash
      - name: Validate policies
        shell: bash
        run: >
          find . -name '*.yaml' -exec mondoo policy validate {} \;