---
name: Lint Policies

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-prod:
    uses: ./.github/workflows/lint-prod.yaml

  lint-edge:
    uses: ./.github/workflows/lint-edge.yaml

  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite@v1.1.3
        with:
          version: v0.16.4

      - name: Check Header Compliance
        run: copywrite headers --plan
