---
name: Lint Policies

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cnspec v10
        run: |
          curl -A "mondoohq/cnspec-policies" -sL -o cnspec9.tgz https://install.mondoo.com/package/cnspec/linux/amd64/tar.gz/latest/download
          tar xfvz cnspec9.tgz
          chmod +x ./cnspec
      - name: Lint OS policies with cnspec 10
        run: |
          cd core
          ../cnspec policy lint .

  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite@v1.1.2
        with:
          version: v0.16.4

      - name: Check Header Compliance
        run: copywrite headers --plan
