---
name: Validate Policies

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Mondoo's cnspec
        run: |
          bash -c "$(curl -sSL https://install.mondoo.com/sh/cnspec)"
        shell: bash
      - name: Validate policies
        shell: bash
        run: >
          find . -name '*.mql.yaml' -exec cnspec bundle validate {} \;